if(NOT FINAL_RELEASE)
  if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../defines.cmake")
    file(COPY_FILE "${CMAKE_CURRENT_LIST_DIR}/default.defines.cmake"
         "${CMAKE_CURRENT_LIST_DIR}/../defines.cmake")
  endif()
  include("${CMAKE_CURRENT_LIST_DIR}/../defines.cmake")
else()
  include("${CMAKE_CURRENT_LIST_DIR}/default.defines.cmake")
endif()

if(SDK_VERSION)
  if(NOT MULTIBUILD_TARGET)
    message("SDK_VERSION: ${SDK_VERSION}")
  endif()
  if(SDK_VERSION STREQUAL "3.3")
    add_definitions(-DSDK_VERSION_3_3)
  elseif(SDK_VERSION STREQUAL "3.4")
    add_definitions(-DSDK_VERSION_3_4)
  elseif(SDK_VERSION STREQUAL "3.5")
    add_definitions(-DSDK_VERSION_3_5)
  endif()
  set(SDKV "-${SDK_VERSION}")
else()
  add_definitions(-DSDK_VERSION_3_3)
endif()

if(NOT PLATFORM)
  if(CMAKE_CXX_COMPILER)
    string(REGEX MATCH "[*]*/(x86_64)-[^/]*" _ ${CMAKE_CXX_COMPILER})
    if(CMAKE_MATCH_1)
      set(PLATFORM "x86_64")
    else()
      string(REGEX MATCH "[*]*/(arm)-[^/]*" _ ${CMAKE_CXX_COMPILER})
      if(CMAKE_MATCH_1)
        set(PLATFORM "arm")
      endif()
    endif()
  endif()
  if(NOT PLATFORM)
    project(empty)
    set(PLATFORM ${CMAKE_SYSTEM_PROCESSOR})
    message("CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
  endif()
endif()

if(PLATFORM STREQUAL "arm")
  add_definitions(-D_FILE_OFFSET_BITS=64)
  add_definitions(-DPATH_MAX=1024)
  if(NOT CMAKE_C_COMPILER STREQUAL
     /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-gcc)
    set(CMAKE_C_COMPILER /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-gcc)
  endif()
  if(NOT CMAKE_CXX_COMPILER STREQUAL
     /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-g++)
    set(CMAKE_CXX_COMPILER
        /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-g++)
  endif()
  if(NOT CMAKE_STRIP STREQUAL
     /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-strip)
    set(CMAKE_STRIP /opt/media-sdk${SDKV}/bin/arm-nic-linux-gnueabihf-strip)
  endif()
  set(SDK_PATH "/opt/media-sdk${SDKV}/arm-nic-linux-gnueabihf")
  add_definitions(-DPLATFORM_arm)
  set(CMAKE_PREFIX_PATH "${SDK_PATH}")
else()
  if(PLATFORM STREQUAL "x86_64")
    set(SDK_PATH "/opt/media-sdk${SDKV}/x86_64-pc-linux-gnu")
    include_directories(BEFORE "${SDK_PATH}/include")
    add_definitions(-DPLATFORM_x86_64)
    set(CMAKE_PREFIX_PATH "${SDK_PATH}/qt6-x86_64")
  else()
    if(PLATFORM STREQUAL "AMD64")
      set(SDK_PATH ${AMD64_SDK_PATH})
      set(CMAKE_PREFIX_PATH "${SDK_PATH}")
    endif()
  endif()
endif()
